Update struct gpio_ops and Add GPIO driver for NXP LS Platforms
OP-TEE/optee_os pull request #4413
Opened 2021-02-23 10:59 UTC by manishtomar1

This pull request does 2 things:
1. Add 'struct gpio_chip *chip' in 'struct gpio_ops' and updated bcm_gpio and pl061_gpio as per modified gpio.h definition.
Based on https://github.com/OP-TEE/optee_os/issues/4007 discussion.
2. Add GPIO driver for NXP LS Platforms

2021-02-24 06:30 UTC, vchong approved these changes
For `core: gpio.h: Add 'struct gpio_chip *chip' in 'struct gpio_ops'`

`Signed-off-by: Victor Chong <victor.chong@linaro.org>`

@sandeepbrcm Would you like to sign off on `bcm_gpio.c` as well?

For `plat-ls: Add GPIO driver for NXP LS Platforms`

`Acked-by: Victor Chong <victor.chong@linaro.org>`

2021-02-25 10:20 UTC, sahilnxp requested changes

2021-02-25 10:20 UTC, sahilnxp commented on core/drivers/ls_gpio.c
> +static const char *gpio_controller_map[GPIO_CTRL_NUM] = {
`static const char * const gpio_controller_map[]`,
With this we can remove `GPIO_CTRL_NUM `also

2021-02-25 10:20 UTC, sahilnxp commented on core/drivers/ls_gpio.c
> +// SPDX-License-Identifier: BSD-2-Clause
It would be good to have description for each function.
Static functions will have description in .c file and other function in .h

2021-02-25 10:20 UTC, sahilnxp commented on core/drivers/ls_gpio.c
> +TEE_Result nxp_gpio_init(struct gpio_chip_data *gpio_data)
change this function name to `ls_gpio_init()` in place of `nxp_gpio_init()`
Please don't use `nxp `prefix, replace it with `ls` at all other places.

2021-02-25 10:20 UTC, sahilnxp commented on core/drivers/ls_gpio.c
> +
Please remove this empty line

2021-02-25 10:20 UTC, sahilnxp commented on core/drivers/ls_gpio.c
> +
Please remove this empty line

2021-02-25 10:20 UTC, sahilnxp commented on core/drivers/ls_gpio.c
> +	/* register NXP-Layerscape GPIO controller  */
Is this correct place for this comment ?

2021-02-25 10:20 UTC, sahilnxp commented on core/drivers/ls_gpio.c
> +
Please remove this empty line

2021-02-25 10:20 UTC, sahilnxp commented on core/include/drivers/ls_gpio.h
> +
Put all code in following block
```
#ifndef __DRIVERS_LS_GPIO_H
#define __DRIVERS_LS_GPIO_H
......
#endif
```

2021-02-25 10:20 UTC, sahilnxp commented on core/include/drivers/ls_gpio.h
> + * struct nxp_gpio_chip describes GPIO controller chip instance
This struct name is `gpio_chip_data `not `nxp_gpio_chip`

2021-03-01 09:03 UTC, manishtomar1 commented
@sandeepbrcm Would you like to sign off on bcm_gpio.c as well?
Please reply.

2021-03-01 09:10 UTC, jforissier commented
> For `core: gpio.h: Add 'struct gpio_chip *chip' in 'struct gpio_ops'`
> 
> `Signed-off-by: Victor Chong <victor.chong@linaro.org>`

What does this mean? Wouldn't an Ack by more appropriate?

2021-03-01 09:18 UTC, vchong commented
> > For `core: gpio.h: Add 'struct gpio_chip *chip' in 'struct gpio_ops'`
> > `Signed-off-by: Victor Chong <victor.chong@linaro.org>`
> 
> What does this mean? Wouldn't an Ack by more appropriate?

Oops. Sorry. I meant to write `Reviewed-by`. @manishtomar1 Please make the appropriate changes when you add tags.

2021-03-01 15:08 UTC, clementfaure requested changes
Please see my comments bellow.
Thanks

2021-03-01 15:08 UTC, clementfaure commented on core/drivers/ls_gpio.c
> + */
This function should only be described in the header file.

2021-03-01 15:08 UTC, clementfaure commented on core/drivers/ls_gpio.c
> + */
```*gpio_data``` description missing

2021-03-01 15:08 UTC, clementfaure commented on core/include/drivers/ls_gpio.h
> +struct gpio_chip_data {
This structure should have ```ls_``` as a prefix

2021-03-01 15:08 UTC, clementfaure commented on core/drivers/ls_gpio.c
> +		io_setbits32(gpio_data->gpio_base + GPIOIBE, 0xffffffff);
```UINT32_MAX``` instead of ```0xffffffff```

2021-03-02 06:58 UTC, manishtomar1 commented
> > > For `core: gpio.h: Add 'struct gpio_chip *chip' in 'struct gpio_ops'`
> > > `Signed-off-by: Victor Chong <victor.chong@linaro.org>`
> > 
> > 
> > What does this mean? Wouldn't an Ack by more appropriate?
> 
> Oops. Sorry. I meant to write `Reviewed-by`. @manishtomar1 Please make the appropriate changes when you add tags.

Taken care.

2021-03-02 07:34 UTC, manishtomar1 commented
> > > For `core: gpio.h: Add 'struct gpio_chip *chip' in 'struct gpio_ops'`
> > > `Signed-off-by: Victor Chong <victor.chong@linaro.org>`
> > 
> > 
> > What does this mean? Wouldn't an Ack by more appropriate?
> 
> Oops. Sorry. I meant to write `Reviewed-by`. @manishtomar1 Please make the appropriate changes when you add tags.

Taken care

2021-03-02 08:37 UTC, clementfaure commented on core/drivers/ls_gpio.c
> + * gpio_data is a pointer of type 'struct ls_gpio_chip_data'.
Minor: I would rather say ```GPIO controller chip instance``` to describe ```gpio_data ```

2021-03-02 08:37 UTC, clementfaure commented on core/drivers/ls_gpio.c
> +/* gpio_data is a pointer of type 'struct ls_gpio_chip_data' */
Not needed, it's already described in the header file

2021-03-02 08:41 UTC, clementfaure approved these changes
```Reviewed-by: Clement Faure <clement.faure@nxp.com>```

2021-03-02 08:44 UTC, sahilnxp commented
`Reviewed-by: Sahil Malhotra <sahil.malhotra@nxp.com>`

2021-03-02 09:43 UTC, jforissier commented
@manishtomar1 I suppose @clementfaure's R-b applies to the first commit too, otherwise he would have mentioned it.

2021-03-02 10:25 UTC, manishtomar1 commented
> @manishtomar1 I suppose @clementfaure's R-b applies to the first commit too, otherwise he would have mentioned it.

Taken care

2021-03-02 12:31 UTC, merged