optee_os: fixes compilation problem with trace level 0
OP-TEE/optee_os pull request #4520
Opened 2021-03-31 14:11 UTC by bitwave

- if CFG_TEE_CORE_LOG_LEVEL in build/common.mk set to zero,
  optee_os doesn't compile
- error is:
```
core/arch/arm/kernel/unwind_arm64.c:77:6: Error: redefinition of »print_kernel_stack«
   77 | void print_kernel_stack(void)
      |      ^~~~~~~~~~~~~~~~~~
in file, included from core/arch/arm/kernel/unwind_arm64.c:35:
core/include/kernel/unwind.h:15:20: Warning: previous definition of »print_kernel_stack« was here
   15 | static inline void print_kernel_stack(void)
      |                    ^~~~~~~~~~~~~~~~~~
```
- to avoid this error we assure the function is not redefined

2021-03-31 14:21 UTC, jforissier reviewed
Hi @bitwave,

Thanks for the patch. Please see my comment below, and also replace the `optee_os:` prefix with`core:` instead and use the imperative mood like so: `core: fix compilation error with trace level 0`

With that:
`Reviewed-by: Jerome Forissier <jerome@forissier.org>`

2021-03-31 14:21 UTC, jforissier commented on core/arch/arm/kernel/unwind_arm64.c
> +
No blank line here please

2021-03-31 14:24 UTC, jforissier commented
We probably want to add a test case for this to `.azure_pipelines.yml` (as a separate patch).

2021-04-01 16:30 UTC, etienne-lms requested changes
**(edited)**
please update commit log to remove special **~~charaters!~~ characters:**
```patch
-core/arch/arm/kernel/unwind_arm64.c:77:6: Error: redefinition of »print_kernel_stack«
+core/arch/arm/kernel/unwind_arm64.c:77:6: Error: redefinition of 'print_kernel_stack'
    77 | void print_kernel_stack(void)
       |      ^~~~~~~~~~~~~~~~~~
 in file, included from core/arch/arm/kernel/unwind_arm64.c:35:
-core/include/kernel/unwind.h:15:20: Warning: previous definition of »print_kernel_stack« was here
+core/include/kernel/unwind.h:15:20: Warning: previous definition of 'print_kernel_stack" was here   15 | static inline void print_kernel_stack(void)
       |                    ^~~~~~~~~~~~~~~~~~
-- to avoid this error we assure the function is not redefined
+
+To avoid this error we ensure the function is not redefined.
```

2021-04-01 16:34 UTC, etienne-lms requested changes
.

2021-04-01 17:06 UTC, bitwave commented
done

2021-04-01 17:10 UTC, etienne-lms approved these changes

2021-04-02 09:12 UTC, merged