[RFC] Added I2C4 Support in IMX I2C Driver.
OP-TEE/optee_os pull request #4702
Opened 2021-06-24 08:50 UTC by DevendraDevadiga

Added the I2C4 support in IMX I2C Driver.
Signed-off-by: Devendra Devadiga<devendradevadiga01@gmail.com>

2021-06-28 12:03 UTC, DevendraDevadiga commented
Dear Sir,
Any comment on this pull request?
Regards,
Devendra Devadiga

2021-06-28 12:41 UTC, jforissier requested changes
Hi @DevendraDevadiga ,

Thank you for the patch!
- Please see my comment below
- For the commit subject the imperative mood is preferred: "Add I2C4 support in IMX I2C driver".
- Some text is needed in the commit description.
- Your Signed-off-by: is required (see [here](https://optee.readthedocs.io/en/latest/general/contribute.html)).

Tagging @OP-TEE/plat-imx for any platform-specific comments.

2021-06-28 12:41 UTC, jforissier commented on core/drivers/imx_i2c.c
> +#if defined(CFG_MX6ULL)
This change doesn't seem related to the main purpose (add I2C4 support)? Therefore,  it should be moved to a separate commit.

2021-06-29 16:03 UTC, DevendraDevadiga commented
Dear Sir,
Thanks for the comment.
Updated the patch as per suggestion.

Regards,
Devendra Devadiga

2021-06-30 07:17 UTC, jforissier commented
This looks OK to me in general but I have no idea about the platform specifics so any plat-imx reviewer please feel free to comment.

`Acked-by: Jerome Forissier <jerome@forissier.org>`

2021-06-30 12:33 UTC, jforissier approved these changes

2021-06-30 13:23 UTC, jforissier commented
@DevendraDevadiga please squash the commits into a single one and add my Acked-by: tag to the commit description.

2021-06-30 13:44 UTC, clementfaure commented
Hi @DevendraDevadiga ,
I would split your work into two commits,

One for the register and offset values ```imx: add I2C4 registers values for imx...``` on which you have my ```Reviewed-by: Clement Faure <clement.faure@nxp.com>```
The other one for the ```imx_i2c``` driver where you can ask @ldts for a review .

2021-06-30 14:40 UTC, ldts commented
also it seems you found a bug on the imx6.h (I2C3 address).
would you mind having that as a separate patch as well?

2021-07-01 10:40 UTC, ldts commented
please squash the commits in 3 separate ones so they can be reviewed (at the moment you are trying to merge 12 commits on your PR)
also please separate the commit header from the message (seems they are on the same line)

2021-07-01 14:31 UTC, ldts commented
please squash the commits in 3 separate ones so they can be reviewed (at the moment you are trying to merge 12 commits on your PR)
also please separate the commit header from the message (seems they are on the same line)

2021-07-02 12:43 UTC, ldts commented
check the section on squashing commits: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
one you have the three commits that we need (with a title and some comment on the body), just force push it to the github branch so history is rewritten.

2021-07-02 12:53 UTC, jforissier commented
@ldts +1

@DevendraDevadiga  a summary of the procedure is given at https://optee.readthedocs.io/en/latest/general/contribute.html#finalizing-your-contribution

2021-07-02 18:56 UTC, closed without merging

2021-07-02 19:05 UTC, DevendraDevadiga commented
I am facing issue in git squashing commands. So closing this request. Sorry for inconvenience caused.

2021-07-02 19:22 UTC, DevendraDevadiga commented
I shared the required patch files.
[optee-imx-i2c4-patch.zip](https://github.com/OP-TEE/optee_os/files/6756595/optee-imx-i2c4-patch.zip)

2021-07-06 11:48 UTC, ldts commented
@DevendraDevadiga let me try creating the branch for you, please do not give up. if you can pull an test that would be great. 
then just fork it and send the PR again? I can then take it from there if you want 
https://github.com/ldts/optee_os/commits/i2c4-devendra