core: drivers: fix some bug in HiSilicon TRNG
OP-TEE/optee_os pull request #6464
Opened 2023-11-15 01:39 UTC by loubaihui

Fix some bug in hisi_trng.c

2023-11-15 09:08 UTC, jenswi-linaro reviewed
Please be more specific in the commit message. 
A "Fixes:" tag pointing to the commit introducing the problem would be nice too.

2023-11-15 12:41 UTC, etienne-lms reviewed
Please add `Fixes: fb5592f9cfeb ("core: drivers: add HiSilicon TRNG implementation")` tag in the commit message.

Could you also append a commit to add a `_make PLATFORM=d06` command in _.github/workflows/ci.yml_ file? It would have catch the issues earlier.

2023-11-15 12:41 UTC, etienne-lms commented on core/drivers/hisi_trng.c
> +	DMSG("TRNG driver init start.");
by the way, could remove the `.` char, here and for all `xMSG()` occurrences in this source file.

2023-11-16 09:17 UTC, loubaihui commented on core/drivers/hisi_trng.c
> +	DMSG("TRNG driver init start.");
> Unrelated change?
Use `DMSG` may be better ?

2023-11-16 09:39 UTC, etienne-lms commented on core/drivers/hisi_trng.c
> +	DMSG("TRNG driver init start.");
This is not a bug, as the commit description mentions. 
It's all fine you make that change but prefer in a separated commit. I think this is what @jenswi-linaro had in mind.

2023-11-16 10:57 UTC, loubaihui commented on core/drivers/hisi_trng.c
> +	DMSG("TRNG driver init start.");
> This is not a bug, as the commit description mentions. It's all fine you make that change but prefer in a separated commit. I think this is what @jenswi-linaro had in mind.
Ok, thank you!

2023-11-17 03:40 UTC, loubaihui commented
> Please add `Fixes: fb5592f9cfeb ("core: drivers: add HiSilicon TRNG implementation")` tag in the commit message.
> 
> Could you also append a commit to add a `_make PLATFORM=d06` command in _.github/workflows/ci.yml_ file? It would have **~catch~ caught** the issues earlier.
> 
> **(edited)**

2023-11-17 03:51 UTC, loubaihui commented
> Please add `Fixes: fb5592f9cfeb ("core: drivers: add HiSilicon TRNG implementation")` tag in the commit message.
> 
> Could you also append a commit to add a `_make PLATFORM=d06` command in _.github/workflows/ci.yml_ file? It would have **~catch~ caught** the issues earlier.
> 
> **(edited)**

Does this need to submit in a new pull request?

2023-11-17 05:23 UTC, etienne-lms commented
> Does this need to submit in a new pull request?

No. You only need to push fixup commits on the same branch you used to created this P-R. Once reviewers are happy, you'll be asked to squash the fixup commits, maybe update commit's messages if needed for a final review before you can applied posted review tags.

2023-11-17 07:58 UTC, etienne-lms reviewed
`Acked-by: Etienne Carriere <etienne.carriere@foss.st.com>` for the series with a fix in commit message for commit "Fixes error use of in IO_READ32_POLL_TIMEOUT() macro in hisi_trng":
```patch
-Fixes error use of in IO_READ32_POLL_TIMEOUT() macro in hisi_trng
+Fixes arguments passed to IO_READ32_POLL_TIMEOUT() macro
+and missing local variable definition in hisi_trng driver.

2023-11-17 07:59 UTC, etienne-lms requested changes
Could you add a 3rd commit that adds a `_make PLATFORM=d06` command in _.github/workflows/ci.yml_ file?

2023-11-18 02:06 UTC, loubaihui commented
> Could you add a 3rd commit that adds a `_make PLATFORM=d06` command in _.github/workflows/ci.yml_ file?

Ok

2023-11-20 14:32 UTC, jforissier commented
> Could you add a 3rd commit that adds a `_make PLATFORM=d06` command in _.github/workflows/ci.yml_ file?

Good suggestion it seems :wink: 

```
_make PLATFORM=d06
In file included from core/arch/arm/include/arm.h:11,
                 from core/arch/arm/include/kernel/delay_arch.h:33,
                 from core/include/kernel/delay.h:33,
                 from core/include/io.h:9,
                 from core/drivers/hisi_trng.c:5:
core/drivers/hisi_trng.c: In function 'hw_get_random_bytes':
lib/libutils/ext/include/util.h:28:13: error: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Werror=sign-compare]
   28 |          _a < _b ? _a : _b; }))
      |             ^
core/drivers/hisi_trng.c:63:24: note: in expansion of macro 'MIN'
   63 |                 size = MIN(HTRNG_BYTES, len - current_len);
      |                        ^~~
```

2023-11-21 14:38 UTC, etienne-lms reviewed
`Acked-by: Etienne Carriere <etienne.carriere@foss.st.com>` for commits
"core: drivers: modify debug and error messages in hisi_trng" and
"ci.yml: adds a PLATFORM=d06 command".

2023-11-21 14:41 UTC, etienne-lms commented
And do not forget to rebase your changes on top of latest master branch. It should resolve the IBART CI test failure.

2023-11-24 01:40 UTC, loubaihui commented
@jforissier

2023-11-24 05:29 UTC, etienne-lms commented
CI make (multi-platform) test failed:
```
_make PLATFORM=d06
core/drivers/hisi_trng.c: In function 'hw_get_random_bytes':
core/drivers/hisi_trng.c:64:17: error: implicit declaration of function 'memcpy' [-Werror=implicit-function-declaration]
   64 |                 memcpy((uint8_t *)buf + current_len, &val, size);
      |                 ^~~~~~
core/drivers/hisi_trng.c:11:1: note: include '<string.h>' or provide a declaration of 'memcpy'
   10 | #include <rng_support.h>
  +++ |+#include <string.h>
   11 |

2023-11-27 09:16 UTC, merged